apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikidb-deployment
spec:
  selector:
    matchLabels:
      app: wikidb
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wikidb
    spec:
      containers:
      - name: mediawiki
        image: 459966755614.dkr.ecr.us-east-2.amazonaws.com/wikidb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wikidb-persistent-volume