apiVersion: v1
kind: Deployment
metadata:
  name: wikidb-deployment
spec:
  selector:
    matchLabels:
      app: wikidb
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: wikidb
    spec:
      containers:
      - name: mediawiki
        image: 459966755614.dkr.ecr.us-east-2.amazonaws.com/wikidb
        ports:
        - containerPort: 3306