apiVersion: v1
kind: PersistentVolume
metadata:
 name: mysql-pv
spec:
 capacity:
   storage: 8Gi
 accessModes:
   - ReadWriteMany
 hostPath:
    path: "/var/lib/mysql"
 persistentVolumeReclaimPolicy: Recycle