apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    name: mysql  
specs:
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: wikidb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-mysql-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi