apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikidb-persistent-volume
  labels:
    app: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
